version: "3.9"

services:
  staffflow-server:
    image: zzhalelov/staffflow-server:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      TZ: Asia/Almaty
      SPRING_DATASOURCE_URL: jdbc:postgresql://staffflow-db:5432/hrms-spring-jpa
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - staffflow-db
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - staffflow-network

  staffflow-db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: hrms-spring-jpa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - staffflow-db-data:/var/lib/postgresql/data
    networks:
      - staffflow-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - staffflow-network
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - staffflow-network
    depends_on:
      - prometheus
    restart: unless-stopped

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    restart: always
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:postgres@staffflow-db:5432/hrms-spring-jpa?sslmode=disable
    ports:
      - "9187:9187"
    networks:
      - staffflow-network

volumes:
  staffflow-db-data:
  grafana-data:

networks:
  staffflow-network:
    driver: bridge
