version: "3.8"

services:
  staffflow-server:
    image: zzhalelov/staffflow-server:latest
    container_name: staffflow-server
    restart: always
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - TZ=Asia/Almaty
      - SPRING_DATASOURCE_URL=jdbc:postgresql://staffflow-db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - staffflow-db

  staffflow-db:
    image: postgres:15-alpine
    container_name: staffflow-db
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - staffflow-db-data:/var/lib/postgresql/data

volumes:
  staffflow-db-data: